export interface Song {
  title: string;
}

export const songs: Song[] = [
  { title: 'Wonderchild' },
  { title: 'Stor mand' },
  { title: 'Maneater' }, // Mente
  { title: 'Ung Kniv' },
  { title: 'Respect' },
  { title: 'Love on top' },
  { title: 'Tilbud' },
  { title: 'Bet on it' },
  { title: 'Love will keep you warm' },
  { title: 'Locked out of heaven' },
  { title: 'When love takes over' },
  { title: 'Neonlys' },
  { title: 'Flammer rammer' },
  { title: 'Gimme more' },
  { title: 'Menneskesøn' },
  { title: 'Senorita' },
  { title: 'Turn red' },
  { title: 'Say so' },
  { title: 'All my love' },
  { title: 'Dance the night' },
  { title: 'Toxicty' },
  { title: 'Love song' },
  { title: 'Take 5' },
  { title: 'Tju bang chokolademand' },
  { title: 'Intet stopper helt' },
  { title: 'Dancing queen' },
  { title: 'Speed dance' },
  { title: 'Fat bottomed girls' },
  { title: 'Passionfruit' },
  { title: 'Mean' },
  { title: 'Piger med pistoler' },
  { title: 'What makes you beautiful' },
  { title: 'Starboy' },
  { title: 'Drenge som mig' },
  { title: 'LA DANZA' },
  { title: 'Fireflies' },
  { title: 'Hey shorty' },
];
