export interface Song {
  title: string;
}

export const songs: Song[] = [
  { title: 'Wonderchild' },
  { title: 'Stor mand' },
  { title: 'Maneater' }, // Mente
  { title: 'Ung Kniv' },
  { title: 'Respect' },
  { title: 'Love on top' },
  { title: 'Tilbud' },
  { title: 'Bet on it' },
  { title: 'Love will keep you warm' },
  { title: 'Locked out of heaven' },
  { title: 'When love takes over' },
  { title: 'Neonlys' },
  { title: 'Flammer rammer' },
  { title: 'Gimme more' },
  { title: 'Menneskesøn' },
  { title: 'Senorita' },
  { title: 'Turn red' },
  { title: 'Say so' },
  { title: 'All my love' },
  { title: 'Dance the night' },
  { title: 'Toxicty' },
  { title: 'Love song' },
  { title: 'Take 5' },
  { title: 'Tju bang chokolademand' },
  { title: 'Intet stopper helt' },
  { title: 'Dancing queen' },
  { title: 'Speed dance' },
  { title: 'Fat bottomed girls' },
  { title: 'Passionfruit' },
  { title: 'Mean' },
  { title: 'Piger med pistoler' },
  { title: 'What makes you beautiful' },
  { title: 'Starboy' },
  { title: 'Drenge som mig' },
  { title: 'LA DANZE' },
  { title: 'Fireflies' },
  { title: 'Hey shorty' },

  // { title: 'Shape of You', artist: 'Ed Sheeran' },
  // { title: 'Someone Like You', artist: 'Adele' },
  // { title: 'Bohemian Rhapsody', artist: 'Queen' },
  // { title: 'Billie Jean', artist: 'Michael Jackson' },
  // { title: 'Dance Monkey', artist: 'Tones and I' },
  // { title: 'Blinding Lights', artist: 'The Weeknd' },
  // { title: 'Hotel California', artist: 'Eagles' },
  // { title: 'Rolling in the Deep', artist: 'Adele' },
  // { title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee' },
  // { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars' },
  // { title: 'Imagine', artist: 'John Lennon' },
  // { title: 'Havana', artist: 'Camila Cabello ft. Young Thug' },
  // { title: 'Wonderwall', artist: 'Oasis' },
  // { title: 'Radioactive', artist: 'Imagine Dragons' },
  // { title: 'Shallow', artist: 'Lady Gaga, Bradley Cooper' },
];
